# Generated by Django 3.1.2 on 2020-10-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_studets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='studets',
            new_name='students',
        ),
    ]
